# for module compiling
import os
from building import *

components = ['UARTDriver']

objs = []
cwd = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    print('item:' + item)

    if not item in components:
        continue

    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
