from building import *

cwd = GetCurrentDir()

src = Glob('*.cpp')

src += Glob('example/*.cpp')

# The set of source files associated with this SConscript file.
path = [cwd, cwd + '/..', cwd + '/../..']

group = DefineGroup('UARTDriver', src, depend=[''], CPPPATH=path)

Return('group')
