import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/stm32h7xx_hal_msp.c
''')

# if GetDepend(['BSP_USING_ETH']):
#     src += Glob('ports/phy_reset.c')

# if GetDepend(['BSP_USING_QSPI_FLASH']):
#     src += Glob('ports/drv_qspi_flash.c')

# if GetDepend(['BSP_USING_SDCARD']):
#     src += Glob('ports/sdcard_port.c')

path =  [cwd]
path += [cwd + '/CubeMX_Config/Inc']

startup_path_prefix = SDK_LIB

if rtconfig.CROSS_TOOL == 'gcc':
    src += [startup_path_prefix + '/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc/startup_stm32h753xx.s']

CPPDEFINES = ['STM32H753xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')