import rtconfig
from building import *

cwd     = GetCurrentDir()
src     = Split("""
main.c
""")

# if GetDepend(['RT_USING_CPLUSPLUS']):
#     src += Glob('*.cpp')

inc = [cwd]

group = DefineGroup('Applications', src, depend = [''],CPPPATH = inc)

Return('group')
